project:
  title: "ConformalPrediction.jl"
  execute-dir: project
  
crossref:
  fig-prefix: Figure
  tbl-prefix: Table
bibliography: bib.bib
fig-format: png

execute: 
  freeze: auto
  eval: true
  echo: true
  output: false

jupyter: julia-1.10

