name = "ConformalPrediction"
uuid = "98bfc277-1877-43dc-819b-a3e38c30242f"
authors = ["Patrick Altmeyer and contributors"]
version = "0.1.13"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ComputationalResources = "ed09eef8-17a6-5b46-8889-db040fac31e3"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
InferOpt = "4846b161-c94e-4150-8dac-c7ae193c601f"
LaplaceRedux = "c52c1a26-f7c5-402b-80be-ba1e638ad478"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJEnsembles = "50ed68f4-41fd-4504-931a-ed422449fee0"
MLJFlux = "094fc8d1-fd35-5302-93ea-dabda2abf845"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Aqua = "0.8"
CategoricalArrays = "0.10"
ChainRules = "1.49.0"
ComputationalResources = "0.3"
Distributions = "0.25.109"
Flux = "0.13, 0.14"
InferOpt = "0.6.1"
LaplaceRedux = "1.0.2"
LinearAlgebra = " 1.9, 1.10"
MLJBase = "0.20, 0.21, 1"
MLJEnsembles = "0.3.3, 0.4"
MLJFlux = "0.2.10, 0.3, 0.4, 0.5"
MLJLinearModels = "0.10.0"
MLJModelInterface = "1"
MLUtils = "0.4.2"
ProgressMeter = "1"
Random = "1.9, 1.10"
StatsBase = "0.33, 0.34.0"
Tables = "1"
Test = "1.9, 1.10"
julia = "1.9, 1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
